### ISSUE TITLE
Signal Monitor

### ISSUE THREAD

**Issue by nnarain** [nnarain/ican#30]
Decode signals and render to TUI

```toml
[signals]
foo = {id: 0x123, bit_offset: 0, bit_length: 8, scale: 1.0, offset: 0.0}
```
